services:
  eir:
    image: ghcr.io/st0o0/eir:latest
    container_name: eir
    restart: unless-stopped
    environment:
      EIR_MASTERS: bifrost
    ports:
      - "9550:9550"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
